# @format
server:
  port: 8089

eureka:
  client:
    service-url:
      defaultZone: ${REGISTRY_SERVICE_HOST:http://localhost:8081/eureka}
spring:
  application:
    name: IDENTITY-SERVICE
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_IDENTITY_CONNECTION:jdbc:mysql://localhost:3306/user}
    username: ${DB_IDENTIY_USERNAME:root}
    password: ${DB_IDENTITY_PASSWORD:123456}
  jpa:
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost:9094}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID:Ov23liitt20qjqsXmTj4}
            client-secret: ${GITHUB_CLIENT_SECRET:b0524b81d48a0fa9b9052ec4bfedbe7bf077aeab}
          google:
            client-id: ${GOOGLE_CLIENT_ID:1031581665110-c3gqpjv79925umrisiap27qqtvomus04.apps.googleusercontent.com}
            client-secret: ${GOOGLE_CLIENT_SECRET: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}
#  docker for database identity:  docker run -dp 3306:3306 --name identity -e MYSQL_ROOT_PASSWORD=123456 mysql

jwt:
  rsa-private-key: classpath:certs/privateKey.pem
  rsa-public-key: classpath:certs/publicKey.pem

logging:
  level:
    org.springframework.security: trace

app:
  service:
    core-banking-url: ${CORE_BANKING_SERVICE_HOST:http://localhost:8083/}
    core-banking-name: core-banking-service
