# @format

app:
  identityUrl: http://localhost:8089

server.port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: NOTIFICATION-SERVICE
          uri: http://localhost:8087
          predicates:
            - Path=/notification/**
          filters:
            - StripPrefix=1
        - id: IDENTITY-SERVICE
          uri: http://localhost:8089
          # uri: lb://identity-service:8089
          predicates:
            - Path=/identity/**
          filters:
            - StripPrefix=1
        - id: core-banking-service
          uri: http://localhost:8083
          predicates:
            - Path=/core-banking/**
          filters:
            - StripPrefix=1
        - id: fund-transfer-service
          uri: http://localhost:8085
          predicates:
            - Path=/fund-transfer/**
          filters:
            - StripPrefix=1
        - id: utility-payment-service
          uri: http://localhost:8086
          predicates:
            - Path=/utility-payment/**
          filters:
            - StripPrefix=1

jwt:
  rsa-private-key: classpath:certs/privateKey.pem
  rsa-public-key: classpath:certs/publicKey.pem

logging:
  level:
    org.springframework.security: trace
