# @format

server.port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: identity-service
          uri: ${IDENTITY_ROUTE_URI:http://localhost:8089}
          predicates:
            - Path=/identity/**
          filters:
            - StripPrefix=1
        - id: core-banking-service
          uri: http://localhost:8083
          predicates:
            - Path=/core-banking/**
          filters:
            - StripPrefix=1
        - id: fund-transfer-service
          uri: http://localhost:8085
          predicates:
            - Path=/fund-transfer/**
          filters:
            - StripPrefix=1
        - id: utility-payment-service
          uri: http://localhost:8086
          predicates:
            - Path=/utility-payment/**
          filters:
            - StripPrefix=1
