# @format

app:
  identityUrl: ${IDENTITY_HOST:http://localhost:8089}

server.port: 8082
eureka:
  client:
    service-url:
      defaultZone: ${SERVICE_REGISTRY_HOST:http://localhost:8081/eureka}

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: NOTIFICATION-SERVICE
          uri: ${NOTIFICATION_SERVICE_HOST:http://localhost:8087}
          predicates:
            - Path=/notification/**
          filters:
            - StripPrefix=1
        - id: IDENTITY-SERVICE
          uri: ${IDENTITY_HOST:http://localhost:8089}
          # uri: lb://identity-service:8089
          predicates:
            - Path=/identity/**
          filters:
            - StripPrefix=1
        - id: core-banking-service
          uri: ${CORE_BANKING_SERVICE_HOST:http://localhost:8083}
          predicates:
            - Path=/core-banking/**
          filters:
            - StripPrefix=1
        - id: fund-transfer-service
          uri: ${FUND_TRANFER_SERVICE_HOST:http://localhost:8085}
          predicates:
            - Path=/fund-transfer/**
          filters:
            - StripPrefix=1
        - id: utility-payment-service
          uri: ${UTILITY_PAYMENT_SERVICE_HOST:http://localhost:8086}
          predicates:
            - Path=/utility-payment/**
          filters:
            - StripPrefix=1

jwt:
  rsa-private-key: classpath:certs/privateKey.pem
  rsa-public-key: classpath:certs/publicKey.pem

logging:
  level:
    org.springframework.security: trace
