# @format

server:
  port: 8087

eureka:
  client:
    service-url:
      defaultZone: ${REGISTRY_SERVICE_HOST:http://localhost:8081/eureka}

spring:
  application:
    name: notification-service
  data:
    mongodb:
      uri: ${DB_NOTIFICATION_CONNECTION:mongodb://root:123456@localhost:27017/notification?authSource=admin}
  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost:9094}
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:nguyenthanhthien0507@gmail.com}
    password: ${MAIL_PASSWORD:xfkjfhrijlrafwsr}
    properties:
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
