# @format

server:
  port: 8085

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  application:
    name: FUND-TRANSFER-SERVICE
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/fund_transfer
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
#  docker for database fund transfer:  docker run -dp 3308:3306 --name fund-transfer -e MYSQL_ROOT_PASSWORD=123456 mysql

rabbitmq:
  queue:
    name: message-queue
    json:
      name: message-queue-json
  exchange:
    name: message-exchange
  routing:
    key: message-queue-routing-key
    json:
      key: message-queue-routing-json-key