# @format
server:
  port: 6666

spring:
  datasource:
    url: jdbc:mysql://localhost:3333
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  application:
    name: Logistic

logging:
  level:
    org:
      springframework:
        jdbc: Info
    sql: Info
# docker run -dp 3333:3306 --name logistic -e MYSQL_ROOT_PASSWORD:123456 mysql
