# @format

FROM maven:3.9.8-amazoncorretto-17-al2023 AS build

WORKDIR /app

COPY pom.xml .

COPY src ./src

RUN mvn package -DskipTests


FROM amazoncorretto:17.0.12-al2023

WORKDIR /app

COPY --from=build /app/target/*.jar app.jar

ENTRYPOINT [ "java", "-jar", "app.jar" ]
