server:
    port: 8087

spring:
    cloud:
        config:
            server:
                git:
                    uri:
                    search-paths: configuration
                    default-label: main